/**:
  ros__parameters:
    Odom/Strategy: "0"
    Odom/ScanKeyFrameThr: "0.0"
    RGBD/LinearUpdate: "0.01"
    RGBD/AngularUpdate: "0.01"
    subscribe_depth: true
    subscribe_rgb: true
    subscribe_odom: false
    frame_id: "camera_link"
    odom_frame_id: "odom"
    map_frame_id: "map"
    approx_sync: true
    qos_image: 2
    qos_camera_info: 2
